
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package soul.general_master.service;

import java.util.Set;
import javax.ws.rs.core.Application;
import org.glassfish.jersey.media.multipart.MultiPartFeature;

/**
 *
 * @author soullab
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        // following code can be used to customize Jersey 2.0 JSON provider:
        try {

            Class jsonProvider = Class.forName("org.glassfish.jersey.jackson.JacksonFeature");
           // Class jsonProvider = Class.forName("com.fasterxml.jackson.jaxrs.json.annotation.JacksonFeatures");
            resources.add(jsonProvider);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        addRestResourceClasses(resources);
         resources.add(MultiPartFeature.class);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
               resources.add(soul.acquisition.suggestions.service.AAccessionFacadeREST.class);
        resources.add(soul.acquisition.suggestions.service.AInvoiceFacadeREST.class);
        resources.add(soul.acquisition.suggestions.service.AOrderFacadeREST.class);
        resources.add(soul.acquisition.suggestions.service.AOrdermasterFacadeREST.class);
        resources.add(soul.acquisition.suggestions.service.APaymentFacadeREST.class);
        resources.add(soul.acquisition.suggestions.service.AReceiveFacadeREST.class);
        resources.add(soul.acquisition.suggestions.service.ARequestFacadeREST.class);
        resources.add(soul.catalogue.service.AuthoritybiblidetailsFacadeREST.class);
        resources.add(soul.catalogue.service.AuthoritysubfieldFacadeREST.class);
        resources.add(soul.catalogue.service.AuthoritytagFacadeREST.class);
        resources.add(soul.catalogue.service.AuthoritytemplateFacadeREST.class);
        resources.add(soul.catalogue.service.AuthoritytemplatemainFacadeREST.class);
        resources.add(soul.catalogue.service.BiblidetailsFacadeREST.class);
        resources.add(soul.catalogue.service.BiblidetailsLocationFacadeREST.class);
        resources.add(soul.catalogue.service.BiblifilesFacadeREST.class);
        resources.add(soul.catalogue.service.BiblisubfieldFacadeREST.class);
        resources.add(soul.catalogue.service.BiblitagFacadeREST.class);
        resources.add(soul.catalogue.service.BiblitemplateFacadeREST.class);
        resources.add(soul.catalogue.service.BiblitemplatemainFacadeREST.class);
        resources.add(soul.catalogue.service.ClassificationschemeFacadeREST.class);
        resources.add(soul.catalogue.service.LocationFacadeREST.class);
        resources.add(soul.catalogue.service.MBkstatusFacadeREST.class);
        resources.add(soul.catalogue.service.ReporttemplatemainFacadeREST.class);
        resources.add(soul.catalogue.service.RpttemplateFacadeREST.class);
        resources.add(soul.catalogue.service.TMissingBiblocationFacadeREST.class);
        resources.add(soul.catalogue.service.TMissingFacadeREST.class);
        resources.add(soul.catalogue.service.Tplfxfld008FacadeREST.class);
        resources.add(soul.catalogue.service.TplldrFacadeREST.class);
        resources.add(soul.circulation.service.BiblocationIssueReserveFacadeREST.class);
        resources.add(soul.circulation.service.BookTransferBiblocationFacadeREST.class);
        resources.add(soul.circulation.service.CtgryMediaIssueReserveFacadeREST.class);
        resources.add(soul.circulation.service.IllExtissueBiblocationFacadeREST.class);
        resources.add(soul.circulation.service.IllExtissueFacadeREST.class);
        resources.add(soul.circulation.service.IllExtissuedmpFacadeREST.class);
        resources.add(soul.circulation.service.IllReqprocdmpFacadeREST.class);
        resources.add(soul.circulation.service.IllRqstmstFacadeREST.class);
        resources.add(soul.circulation.service.IssuedInformationFacadeREST.class);
        resources.add(soul.circulation.service.MGroupFacadeREST.class);
        resources.add(soul.circulation.service.MMemberFacadeREST.class);
        resources.add(soul.circulation.service.MemPhotoFacadeREST.class);
        resources.add(soul.circulation.service.MemcardtemplatemainFacadeREST.class);
        resources.add(soul.circulation.service.MemcardtemplatesubFacadeREST.class);
        resources.add(soul.circulation.service.ReserveBiblocationFacadeREST.class);
        resources.add(soul.circulation.service.TBInvoiceFacadeREST.class);
        resources.add(soul.circulation.service.TBPaymentFacadeREST.class);
        resources.add(soul.circulation.service.TBindingFacadeREST.class);
        resources.add(soul.circulation.service.TBookTransferFacadeREST.class);
        resources.add(soul.circulation.service.TBookbankissuereturnFacadeREST.class);
        resources.add(soul.circulation.service.TDamageFacadeREST.class);
        resources.add(soul.circulation.service.TGroupIssueFacadeREST.class);
        resources.add(soul.circulation.service.TIssueFacadeREST.class);
        resources.add(soul.circulation.service.TLostFacadeREST.class);
        resources.add(soul.circulation.service.TMemdueFacadeREST.class);
        resources.add(soul.circulation.service.TMemfineFacadeREST.class);
        resources.add(soul.circulation.service.TMemlogFacadeREST.class);
        resources.add(soul.circulation.service.TMemrcptFacadeREST.class);
        resources.add(soul.circulation.service.TOtherissueFacadeREST.class);
        resources.add(soul.circulation.service.TOtherreturnFacadeREST.class);
        resources.add(soul.circulation.service.TReceiveFacadeREST.class);
        resources.add(soul.circulation.service.TReplaceFacadeREST.class);
        resources.add(soul.circulation.service.TReserveFacadeREST.class);
        resources.add(soul.circulation.service.TStockvarificationFacadeREST.class);
        resources.add(soul.circulation.service.TWithdrawFacadeREST.class);
        resources.add(soul.circulation_master.service.MCalenderFacadeREST.class);
        resources.add(soul.circulation_master.service.MCtgryColllectionFacadeREST.class);
        resources.add(soul.circulation_master.service.MCtgryFacadeREST.class);
        resources.add(soul.circulation_master.service.MCtgryMediaFacadeREST.class);
        resources.add(soul.circulation_master.service.MTypeFacadeREST.class);
        resources.add(soul.circulation_master.service.MWeekoffdayFacadeREST.class);
        resources.add(soul.cross.filter.CrossFilter.class);
        resources.add(soul.errorresponse.service.SoulExceptionMapper.class);
        resources.add(soul.general_master.service.AAmtReceiveFacadeREST.class);
        resources.add(soul.general_master.service.ABudgetFacadeREST.class);
        resources.add(soul.general_master.service.ABudgetTransactionFacadeREST.class);
        resources.add(soul.general_master.service.ACurrencyFacadeREST.class);
        resources.add(soul.general_master.service.ASupplierDetailFacadeREST.class);
        resources.add(soul.general_master.service.AutogenerateFacadeREST.class);
        resources.add(soul.general_master.service.BHeadsFacadeREST.class);
        resources.add(soul.general_master.service.BkSubjectFacadeREST.class);
        resources.add(soul.general_master.service.CountrymasterFacadeREST.class);
        resources.add(soul.general_master.service.IllLibmstFacadeREST.class);
        resources.add(soul.general_master.service.IllLibrestrictFacadeREST.class);
        resources.add(soul.general_master.service.LanguagemasterFacadeREST.class);
        resources.add(soul.general_master.service.LetterFormatsFacadeREST.class);
        resources.add(soul.general_master.service.LibmaterialsFacadeREST.class);
        resources.add(soul.general_master.service.MBranchFacadeREST.class);
        resources.add(soul.general_master.service.MBranchmasterFacadeREST.class);
        resources.add(soul.general_master.service.MFcltydeptFacadeREST.class);
        resources.add(soul.general_master.service.ReportimageFacadeREST.class);
        resources.add(soul.serialControl.service.SLooseissuemappingFacadeREST.class);
        resources.add(soul.serialControl.service.SMstFacadeREST.class);
        resources.add(soul.serialControl.service.SMstInScheduleFacadeREST.class);
        resources.add(soul.serialControl.service.SOthertitleFacadeREST.class);
        resources.add(soul.serialControl.service.SParallelFacadeREST.class);
        resources.add(soul.serialControl.service.SPaymentFacadeREST.class);
        resources.add(soul.serialControl.service.SRequestFacadeREST.class);
        resources.add(soul.serialControl.service.SScheduleFacadeREST.class);
        resources.add(soul.serialControl.service.SSubInvFacadeREST.class);
        resources.add(soul.serialControl.service.SSubInvdetailFacadeREST.class);
        resources.add(soul.serialControl.service.SSubdetailFacadeREST.class);
        resources.add(soul.serialControl.service.SSubscriptionFacadeREST.class);
        resources.add(soul.serial_master.service.SBindingFacadeREST.class);
        resources.add(soul.serial_master.service.SBindingSetFacadeREST.class);
        resources.add(soul.serial_master.service.SBindparaFacadeREST.class);
        resources.add(soul.serial_master.service.SEditionFacadeREST.class);
        resources.add(soul.serial_master.service.SFrequencyFacadeREST.class);
        resources.add(soul.serial_master.service.SInvoiceFacadeREST.class);
        resources.add(soul.serial_master.service.SModeFacadeREST.class);
        resources.add(soul.serial_master.service.SSupplierDetailFacadeREST.class);
        resources.add(soul.serial_master.service.SSupplierFacadeREST.class);
        resources.add(soul.sru.service.SruHttpClient.class);
        resources.add(soul.sru.service.SruserverFacadeREST.class);
        resources.add(soul.system_setting.service.AccessionCtypeFacadeREST.class);
        resources.add(soul.system_setting.service.AdminMailFacadeREST.class);
        resources.add(soul.system_setting.service.EsconfigurationFacadeREST.class);
        resources.add(soul.system_setting.service.MLablespectsFacadeREST.class);
        resources.add(soul.system_setting.service.SmsmastersubFacadeREST.class);
        resources.add(soul.user_setting.service.PrivilegeFacadeREST.class);
        resources.add(soul.user_setting.service.SgroupFacadeREST.class);
        resources.add(soul.user_setting.service.UserdetailFacadeREST.class);
    }
}
